CREATE TABLE virksomheder (
    navnelbnr INT PRIMARY KEY,
    cvrnr BIGINT,
    pnr BIGINT,
    brancheKode VARCHAR(50),
    branche TEXT,
    virksomhedstype VARCHAR(100),
    navn1 TEXT,
    adresse1 TEXT,
    postnr INT,
    city VARCHAR(100),
    seneste_kontrol INT,
    seneste_kontrol_dato DATETIME,
    naestseneste_kontrol INT,
    naestseneste_kontrol_dato DATETIME,
    tredjeseneste_kontrol INT,
    tredjeseneste_kontrol_dato DATETIME,
    fjerdeseneste_kontrol INT,
    fjerdeseneste_kontrol_dato DATETIME,
    URL VARCHAR(255),
    reklame_beskyttelse BOOLEAN,
    Elite_Smiley BOOLEAN,
    Kaedenavn TEXT,
    Pixibranche TEXT
);