name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Upload files to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftp://${{ secrets.FTP_SERVER }}:${{ secrets.FTP_PORT }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html
